### Register User
POST http://localhost:9090/register
Content-Type: application/json

{
  "username": "harsh2",
  "password": "123456",
  "email": "h2@gmail.com",
  "name": "harsh"
}

###

### Login User
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "h2@gmail.com",
  "password": "123456"
}

###

### Get User Profile
GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
"token":  "b99f4efb3021e63465145656f71a70c4c983cadd1dc453b1ce552581613405fe"
}

###

### Update User Profile
POST http://localhost:9090/user_update
Content-Type: application/json

{
  "token":"a8d03d40019aa5ba2ec5a15f073112633cfc3fe94299847d2ff05809e7f8bd4d",
  "bio": "Data Scientist",
  "currentPost": "Intern at Oasis Infobyte"
}



###

### Update Profile Data
POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
   "token": "a8d03d40019aa5ba2ec5a15f073112633cfc3fe94299847d2ff05809e7f8bd4d",
   "bio": "Java Full Stack Developer | MERN • SQL • JavaScript • Open Source Enthusiast",
   "currentPost": "Data Scientist Intern at Oasis Infobyte",
   "pastWork": [
     {
       "company": "Microsoft Intern",
       "position": "Web Developer Intern",
       "years": "July 2024 - August 2024"
     },
     {
       "company": "Open Source",
       "position": "Contributor",
       "years": "2024 - Present"
     }
   ],
   "education": [
     {
       "school": "Delhi University (School of Open Learning)",
       "degree": "B.A.",
       "fieldOfStudy": "Humanities"
     },
     {
       "school": "Self Learning",
       "degree": "Full Stack Development (MERN Stack, SQL, Bootstrap, Tailwind)",
       "fieldOfStudy": "Computer Science"
     }
   ]
 }

###

### GET ALL USERS
GET http://localhost:9090/user/get_all_users

